CREATE TABLE "SYSTEM"."LAYERED_CUSTOMER" 
   (	"CUSTNO" NUMBER NOT NULL ENABLE, 
	"CUSTNAME" VARCHAR2(20 BYTE), 
	"CUSTADDRS" VARCHAR2(20 BYTE), 
	"PAMT" FLOAT(126), 
	"INTRAMT" FLOAT(126), 
	 CONSTRAINT "LAYERED_CUSTOMER_PK" PRIMARY KEY ("CUSTNO")